services:
  mongodb:
    image: mongo:7
    container_name: movie-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nuvem
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: movie-backend
    environment:
      MONGO_URI: mongodb://mongodb:27017/nuvem
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://44.202.24.143:8080
    container_name: movie-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodata: