services:
  backend:
    build: .
    container_name: movie-backend
    environment:
      DB_URL: jdbc:postgresql://projectdatabase.cf1cjjqak9cv.us-east-1.rds.amazonaws.com:5432/movies?sslmode=require
      DB_USER: millie
      DB_PASS: projeto5h11
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://3.86.104.121:8080
    container_name: movie-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend