services:
  backend:
    build: .
    container_name: movie-backend
    environment:
      MONGO_URI: mongodb+srv://clovitoarroyo_db_user:x64g27cWOdPi8om1@cluster0.xa8frev.mongodb.net/myapp?retryWrites=true&w=majority
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://52.202.18.128:8080
    container_name: movie-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend