spring.application.name=nuvem
server.port=8080

spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.boot.context.config=TRACE
logging.level.org.springframework.core.env=DEBUG

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}